spring:
  application:
    name: DEPARTMENT-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/ms_company
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
server:
  port: 8081


#department:
#  request: department.request
#  response: department.response
#  exchange: department.exchange