spring:
  application:
    name: EMPLOYEE-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/ms_company
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
server:
  port: 8080
#rabbitmq:
#  department:
#    queue: department.request
#    exchange: department.exchange
#    routingkey: department.request
